# Generated by Django 3.2.14 on 2022-07-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('label', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
